### ISSUE TITLE
Layer Icons

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#108]
Under the Assessment and Response page, in discussions with Linda and Zlata they proposed that they would have replacement icons for the Affected Schools, Health Centres and Wells, rather than dots. Is it possible to replace these?

**Comment by LindaAlblas** [comment]
We can easily replace the Affected Schools, Health Centres and Wells for [Font Awesome Icons](http://fontawesome.io/icons/). I have listed a few suggestions below. Could you let me know which one you'd like for each layer and also the fill and stroke colours? 

Affected schools: 
- http://fontawesome.io/icon/graduation-cap/
- http://fontawesome.io/icon/building-o/
- http://fontawesome.io/icon/building/

Health centres:
- http://fontawesome.io/icon/hospital-o/
- http://fontawesome.io/icon/user-md/
- http://fontawesome.io/icon/h-square/
- http://fontawesome.io/icon/medkit/

Wells:
- http://fontawesome.io/icon/tint/

**Comment by Happs80** [comment]
Thanks!

I think the 'Health Centre' icon from the Preparadness tab would be suitable for the health centres.

And I like this: http://fontawesome.io/icon/graduation-cap/

And this: http://fontawesome.io/icon/tint/

Appreciated,...

**Comment by LindaAlblas** [comment]
I've updated the styles and given them some colour. Let me know what you think.
