### ISSUE TITLE
DMIS Zoom Level

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#112]
Hi,

When opening the page initially, the zoom level of the map is zoomed out to include parts of vietnam, laos, etc.

Is it possible to zoom in one more click as the default level?

i.e. http://ews1294.info/sensormap

**Comment by LindaAlblas** [comment]
@Happs80 The initial zoom level has been updated. Could you have a look?

**Comment by Happs80** [comment]
Perfect. thanks.
