### ISSUE TITLE
Polygons & Dot Points

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#114]
Hi team,

I noticed when selecting both polygon layer and point layers, that the points are 'hidden' underneath the polygons, so that you can't really see them, and you can't click on them either.

Is it possible to place points and lines above polygons?

**Comment by Happs80** [comment]
Is it possible to make the polygon outline thinner and perhaps 80% grey scale.

Also, the polygon shading, slightly lighter? perhaps 40% grey scale.

**Comment by LindaAlblas** [comment]
Which polygon outlines do you specifically mean? Only the NCDM layers?

**Comment by Happs80** [comment]
Ideally we would have uniformity across the layers.

So the same level of polygon shading that you have for the preparedness tab - demographics.

And the same level of outline as the preparadness tab - district outline.

**Comment by st-mpc** [comment]
I have some changes to the polygon styling.  See answers to comment above.

**'So the same level of polygon shading that you have for the preparedness tab - demographics.'**
 - There are two levels of opacity set in the demographics layer.   The population density is set at 50%; the total population and total households have a 70% opacity.   I have aligned the opacity of all the polygon layers to the higher (70%) value, leaving the population density as is.  

**'And the same level of outline as the preparadness tab - district outline.'**
I have used the stroke width of the district outline, and applied across the layers to give a consistent polygon boundary width.    The district outline is a grey color; when this is applied to the layers some boundaries are hard to see when the polygon fill is also grey.    Hence, I have left the boundary as black but toned the outline down by setting the opacity to 70%, matching the opacity of the polygon fill.

Any throughts?

Martin

**Comment by Happs80** [comment]
I think this looks good now guys. Thank you.

**Comment by st-mpc** [comment]
Hi, 
I have added a polygon boundary to the polyon layers in the Demographics group - Number of total households and Total population.   Polygon boundaries are aligned with the  NDCM layers,  
 I felt that for the Number of total households layer:
  - the lack of polygon boundaries made the extent of the data hard to interpret
 -  the 1000-2000 class was hard to make out against the background mapping
 - the legend looked a bit strange for the <1000 class wihout a polygon boundary. 

The polygon boudaries on the Total population layer may make it look a bit 'busier', but for consistency I have added the boundaries to match the households layer. 
 
Do you think this aids interpretation?   We can easily remove the polygon boundaries if needed. 

Martin
