### ISSUE TITLE
A&R Roads

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#116]
Could we please make the roads on the Assessment and Response tab the same as the roads on the Preparedness tab.

**Comment by LindaAlblas** [comment]
Does the Assessment and Response dataset have the same classification of roads as the on on the Preparedness tab (see below)?

CODE 20 = National Primary Roads
CODE 21 = Secondary Primary Roads
CODE 22 = Primary Provincial Road
CODE 24 = Secondary Provincial Road
CODE 25 = Car Truck
CODE 26 = Footpath
CODE 27 = Bridge

**Comment by Happs80** [comment]
Let me check with the guys and get back to you.

**Comment by Happs80** [comment]
Hi, checked in with the guys, and they confirmed that the data set does indeed contain the same road classification codes.

**Comment by LindaAlblas** [comment]
Thanks. I'll update the style for the Assessment and Response roads layer.

**Comment by st-mpc** [comment]
See PD-87

**Comment by popelnuh** [comment]
The styles have now been updated.
