### ISSUE TITLE
Addition of Settlements dataset

### ISSUE THREAD

**Issue by dcfrankland** [thinkWhere/DMIS#119]
We seem to have missed one static dataset which we should have received during the initial data supply. Could we please add the settlement dataset to the Preparedness Tab, inside the Administrative Boundaries group and style it as per the first layer in this map:

**Comment by dcfrankland** [comment]
https://mangomap.com/chanvibol/maps/34750/humanitarian-response-forum-hrf-cambodia-cods-and-fods#

**Comment by st-mpc** [comment]
@Happs80 
Settlements data has now been added.    This resides on a 'Administrative' tab alongside geographic borders.  I have tried to align the different layer groups between English and Khmer as there were some differences.  Hence, roads sits in a 'Infrastructure' tab (same in Khmer); settlements and geographic borders lie in a 'TODO' tab in Khmer as we need the translation. 

Martin

**Comment by st-mpc** [comment]
Complete.   See PD-89
