### ISSUE TITLE
Layer ordering point - lines - polygons

### ISSUE THREAD

**Issue by dcfrankland** [thinkWhere/DMIS#123]
@LindaAlblas this issue was previously raised by James. I know there is an issue with it's implementation and in order to achieve it a level of hard-coding and some user caveats may be required. Accepting these caveats are we able to reorder the layers in tab of the DMIS application? If so, James will provide a layer order for us to implement.

**Comment by LindaAlblas** [comment]
@Happs80 , the display on the map is now points over lines over polygons
