### ISSUE TITLE
Problem with text formatting on mobile site

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#128]
The mnej text on the mobile site is displaying in tiny font. This is Android and chrome browser.

**Comment by Happs80** [comment]
Menu*

**Comment by LindaAlblas** [comment]
Could you attach a screenshot of what you are seeing please?

**Comment by Happs80** [comment]
Please see here. 

![screenshot_20171016-120419](https://user-images.githubusercontent.com/31128624/31596116-89db80a0-b26a-11e7-948f-133e9a9101b9.png)

**Comment by LindaAlblas** [comment]
@Happs80 this should now be fixed. Could you let me know if it fixed for you too?

**Comment by Happs80** [comment]
yes. fixed now. thank you.
