### ISSUE TITLE
Firefox Display Issue

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#129]
In Firefox. Desktop version. Windows 10.

Preparedness tab. Health centre icon not showing in the menu.

**Comment by popelnuh** [comment]
@Happs80 , we cannot replicate the issue on our side. Could clear cache in your browser and try again and if persists, could you please take a screenshot?

There have been temporary display issues with the 'Evacuation Sites' icon, however, this should now be resolved.

Thank you,

Zlata

**Comment by Happs80** [comment]
ok i cleared cache on the browser and now I cant see anything selected??

![untitled](https://user-images.githubusercontent.com/31128624/31596174-f91b0012-b26a-11e7-91e9-26b8e96edea3.png)

**Comment by LindaAlblas** [comment]
@Happs80 this should be fixed now. Could you let me know if it is working for you too?

**Comment by Happs80** [comment]
Yes! This now looks like it should!

Thank you.

**Comment by LindaAlblas** [comment]
👍
