### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#139]
Hi guys,

Now there are different issues.

The map has zoomed out again on login.

And the tops of the icons are now chopped off in the menu.
![untitled-1](https://user-images.githubusercontent.com/31128624/31663398-28637050-b36c-11e7-904c-1a52aad0174a.jpg)

**Comment by LindaAlblas** [comment]
@Happs80 , we are looking at the issue with the affected health centres and other assessment layers at the moment so it might look funny for the next few hours. I'll let you know when it is back to normal.

**Comment by LindaAlblas** [comment]
Hi @Happs80 , everything should be back to normal now. Sorry for any inconvenience!
