### ISSUE TITLE
One final request

### ISSUE THREAD

**Issue by Happs80** [thinkWhere/DMIS#144]
I think we can delete the 'Map' menu item.

Users can 'View Map' from the front page and then it goes nowhere when you're actually on the map.

**Comment by LindaAlblas** [comment]
@Happs80 this would be easy to change, but how would you get back to the map if you were on the FAQ or admin page for example? You'd have to go to the home page first. Happy to remove it for you but just wanted to flag it up that it might not be a good idea for usability.

**Comment by Happs80** [comment]
Could we just make the top left DMIS image take you to the map?

**Comment by LindaAlblas** [comment]
The logo on the left is the most familiar way for users to navigate to the home page so I'd be careful to do something different to what users expect. See Amazon and Dropbox for example.

**Comment by dcfrankland** [comment]
Hi @Happs80, any more thoughts on this? I must say from my perspective I agree with Linda that this change is potentially counter-intuitive to what the majority of users would expect, and as such would advise against this. However, if you want this to be implemented we can do so. Could you please let us know so we can make the change or otherwise? Cheers.

**Comment by Happs80** [comment]
hi,

i uderstand your reasoning. and i know this isn't 'best practice' for ux design. but the front page is essentially a splash page anyway, so if i was clicking top left, i would want to return to login or map anyway. right?

**Comment by dcfrankland** [comment]
Hi James, from our perspective, no. We believe that clicking top left the user would want to return to the home page. That said, if this is something you'd like to be implemented as a final tweak then we're obviously happy to do so.
