### ISSUE TITLE
Adding New users: Long Password returns 500

### ISSUE THREAD

**Issue by popelnuh** [thinkWhere/DMIS#48]
When I add a new user
And I enter long password into input field
Then I get 500 and '{"Error": "User Create - Unhandled error: password exceeds maximum allowed size"}

**Comment by popelnuh** [comment]
Long password: 64K ^ -1

**Comment by LindaAlblas** [comment]
@popelnuh this should be fixed now

**Comment by popelnuh** [comment]
Fixed now, There is a check on the front end.
